# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('in_param', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('expect', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
            ],
            options={
                'db_table': 't_api_case',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('app_id', models.IntegerField(null=True)),
                ('app_name', models.CharField(max_length=100, null=True)),
                ('page_id', models.IntegerField(null=True)),
                ('page_name', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 't_app',
            },
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=100)),
                ('url', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('case_count', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='最后修改日期')),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_id_app', to='appapi.App')),
                ('page_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_id_app', to='appapi.App')),
            ],
            options={
                'db_table': 't_api',
            },
        ),
        migrations.AddField(
            model_name='apicase',
            name='api',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapi.Interface'),
        ),
    ]
