# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-21 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0003_auto_20170421_2231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppage',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='app_id',
            new_name='app',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='page_id',
            new_name='page',
        ),
    ]
