# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0004_auto_20170421_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='保存日期'),
        ),
    ]
