# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-18 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_auto_20170518_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
