# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0006_auto_20170518_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicase',
            name='execute_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='execute_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
