# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-13 14:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0008_auto_20170522_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 13, 14, 40, 1, 994934), verbose_name='保存日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apppage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 13, 14, 40, 13, 548089), verbose_name='保存日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apppage',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apicase',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
