# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_auto_20170713_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=20)),
                ('case_count', models.TextField(blank=True, null=True)),
                ('pass_count', models.TextField(blank=True, null=True)),
                ('fail_count', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('execute_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_task_list',
            },
        ),
        migrations.AlterField(
            model_name='apicase',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='app',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='apppage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
