# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-31 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0012_tasklist_elapsed_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_id', models.CharField(max_length=20)),
                ('url', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('in_param', models.TextField(blank=True, null=True)),
                ('result', models.TextField(blank=True, null=True)),
                ('expect', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('elapsed_time', models.TextField(blank=True, null=True)),
                ('execute_time', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapi.App')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapi.ApiCase')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appapi.AppPage')),
            ],
            options={
                'db_table': 't_task_report',
            },
        ),
    ]
